### ISSUE TITLE
Documents about this plugin

### ISSUE THREAD

**Issue by sunxinpeng1994** [oxygenxml/dita-ot-css-pdf#12]
Hello,
I can use this plugin now. But if I want to modify it, do we have some documents as instructions? Such as, change cover page or header.
Thanks a lot.

**Comment by raducoravu** [comment]
As the plugin is a part of the DITA Open Toolkit bundled with Oxygen XML Editor the documentation for customizing CSS for print is available on our web site:
https://www.oxygenxml.com/doc/versions/21.1/ug-pdf-css/
