### ISSUE TITLE
Plugin seems to require Saxon-PE

### ISSUE THREAD

**Issue by larrykollar** [oxygenxml/dita-ot-css-pdf#14]
Using DITA-OT v3.1 or v3.2.1, attempting to process a book fails in pdf-css.xslt-pipeline-post-process with these messages:

```
     [xslt] /Users/larry/bin/dita-ot-3.1/plugins/com.oxygenxml.pdf.css/xsl/review/review-utils.xsl:32:54: Warning! saxon:assign is not recognized as a Saxon instruction. Saxon extensions require Saxon-PE or higher
     [xslt] /Users/larry/bin/dita-ot-3.1/plugins/com.oxygenxml.pdf.css/xsl/review/review-utils.xsl:57:54: Warning! saxon:assign is not recognized as a Saxon instruction. Saxon extensions require Saxon-PE or higher
     [xslt] /Users/larry/bin/dita-ot-3.1/plugins/com.oxygenxml.pdf.css/xsl/review/review-utils.xsl:81:52: Warning! saxon:assign is not recognized as a Saxon instruction. Saxon extensions require Saxon-PE or higher
     [xslt] /Users/larry/bin/dita-ot-3.1/plugins/com.oxygenxml.pdf.css/xsl/review/review-utils.xsl:145:96: Warning! saxon:assign is not recognized as a Saxon instruction. Saxon extensions require Saxon-PE or higher
     [xslt] /Users/larry/bin/dita-ot-3.1/plugins/com.oxygenxml.pdf.css/xsl/review/review-utils.xsl:148:86: Warning! saxon:assign is not recognized as a Saxon instruction. Saxon extensions require Saxon-PE or higher
     [xslt] /Users/larry/bin/dita-ot-3.1/plugins/com.oxygenxml.pdf.css/xsl/merged2merged/merged-images.xsl:27:0: Fatal Error! Cannot find a 1-argument function named {java:ImageInfo}getImageSize(). Reflexive calls to Java methods are not available under Saxon-HE
```

Is there a workaround for this?

**Comment by dan-caprioara** [comment]
We are working to make this plugin compatible to DITA-OT 3.x. It will be available in a couple of months, when the oXygen 21 will be released. If you need a beta version, please send us an email using the oXygen support form: https://www.oxygenxml.com/techSupport.html

However, the workaround is to replace the dita-ot-3.1/lib/saxon.jar with one from a from a DITA-OT 2.x distribution.

**Comment by raducoravu** [comment]
Actually replacing the Saxon 9.8 bundled with DITA OT 3.2.1 with Saxon 9.1 does not work out of the fox.
We have a DITA OT 3.1.0 here:

https://github.com/oxygenxml/dita-ot-3x-plugin

which has the DITA to PDF using CSS plugin installed and which works with Saxon 9.1 by patching the DITA OT main library.
So you may want to experiment with our special DITA OT 3.1 distribution or wait for the Oxygen 21 release.

**Comment by larrykollar** [comment]
Thanks, guys. I’ll try that special distribution for now.

Can we leave this open for anyone else who runs across this issue?

**Comment by dan-caprioara** [comment]
Yes, we can leave it until we release the new plugin.

**Comment by raducoravu** [comment]
I uploaded changes to this plugin in order to work with DITA OT 3.x. But we will no longer continue to update this GitHub project as we'll probably ship this plugin in a special DITA OT publishing engine as a separate download on our web site.
