### ISSUE TITLE
Does not work with a single DITA-Topic

### ISSUE THREAD

**Issue by grefel** [oxygenxml/dita-ot-css-pdf#4]
Trying to genereat a single Topic, not a MapI get the following Error:

merged2pdf:

BUILD FAILED
C:\Program Files\Oxygen XML Editor 16\frameworks\dita\DITA-OT\build.xml:53: The following error occurred while executing this line:
C:\Program Files\Oxygen XML Editor 16\frameworks\dita\DITA-OT\plugins\com.sartorius-intec.pdf.prince\build.xml:60: input file C:\Users\hp\Desktop\temp\pdf-prince\stage1a.xml does not exist

Is the Transformation meant to work with single DITA-Topic Files?

**Comment by tofi86** [comment]
Hey Dan, do you have any news regarding this issue?

**Comment by dan-caprioara** [comment]
Hi, for the moment transforming a single topic to PDF is not a priority.

**Comment by raducoravu** [comment]
We decided not to update this open source plugin any more, all the changes along with support for publishing single DITA topics to PDF will be made to the DITA Open Toolkit bundled with Oxygen and to a special DITA Open Toolkit which will be available for download from our website.
